fm_elfinder:
    assets_path: /assets 
    instances:
        default:
            locale: fr # Langue
            editor: ckeditor # Editeur utilisé
            theme: smoothness # Thème à utiliser
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads/images
                        show_hidden: false # Masque les fichiers cachés
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg'] # Fichiers autorisés
                        upload_deny: ['all'] # Fichiers interdits
                        upload_max_size: 2M # Taille maximum